default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build
  - deploy

build_job:
  stage: build
  script: |
    echo "Building the application.."
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t abhinav2173/springboot:$CI_COMMIT_SHA .
    docker push abhinav2173/springboot:$CI_COMMIT_SHA

deploy_job:
  stage: deploy
  script: |
    echo "deploying the application"
    docker pull abhinav2173/springboot:$CI_COMMIT_SHA
    docker rm -f springboot-example || true
    docker run -d -p 8080:8080 --name springboot-example abhinav2173/springboot:$CI_COMMIT_SHA
  tags:
    - ec2-runner
