version: '3.8'

services:
  springboot-app:
    image: abhinav2173/springboot:$CI_COMMIT_SHA
    ports:
      - "8081:8080"
    networks:
      - monitoring
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  prometheus:
    image: prom/prometheus:v2.43.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.0.7
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
